// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBOiMnicGW5U5zPHJQk3cYIbgubqnLWk',
    appId: '1:848395158442:android:39d1f24d7376057a41e1d3',
    messagingSenderId: '848395158442',
    projectId: 'sermon-atlas',
    databaseURL: 'https://sermon-atlas.firebaseio.com',
    storageBucket: 'sermon-atlas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJi8SlihWJmAns4nZVm4xKaT25OpctqL8',
    appId: '1:848395158442:ios:a1d7d222696526db41e1d3',
    messagingSenderId: '848395158442',
    projectId: 'sermon-atlas',
    databaseURL: 'https://sermon-atlas.firebaseio.com',
    storageBucket: 'sermon-atlas.appspot.com',
    iosClientId: '848395158442-3pqcq3719rhqsciqfq6ut3odlq9ah1v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sermonAtlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJi8SlihWJmAns4nZVm4xKaT25OpctqL8',
    appId: '1:848395158442:ios:a1d7d222696526db41e1d3',
    messagingSenderId: '848395158442',
    projectId: 'sermon-atlas',
    databaseURL: 'https://sermon-atlas.firebaseio.com',
    storageBucket: 'sermon-atlas.appspot.com',
    iosClientId: '848395158442-3pqcq3719rhqsciqfq6ut3odlq9ah1v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sermonAtlas',
  );
}
